language: go
go:
  - 1.9.x

sudo: false

before_install:
  - go get github.com/golang/lint/golint

install: true

script:
  - make
  - prove ./ok > ok.txt
  - prove ./fail > fail.txt ; echo "force success"
  - curl -X POST -F file=@ok.txt ocihub.org:8080/oct/oci-cert-demo-ok
  - curl -X POST -F file=@fail.txt ocihub.org:8080/oct/oci-cert-demo-fail
